dataloader:
  data_type: 'heightscan'
  local_data_root: '/home/fanyang1/git/fan_nav/IsaacLab/data/heightscan'
  euler_data_root: '/cluster/scratch/fanyang1/heightscan/DATA'
  image_list: 'local_heightscan_images.txt'
  new_image_shape_hw: [51, 51]
  crop_min: 40
  resize_shape_hw: [51, 51]
  batch_size: 256
  num_workers: 0
  min_depth: -2.0
  max_depth: 2.0
  valid_ratio_threshold: 0.10
  use_augmentation: False
  shuffle: True

training:
  log_space: False
  ENU_frame: False
  init_beta: 0.1
  final_beta: 0.5
  noise_type: 'parametric' # 'baseline', 'parametric'
  epochs: 10
  val_iterations: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  max_pred_len: 16
  noise_prob: 0.0
  load_model: False
  pretrain_vae: False
  is_train: False
  save_model: True
  is_wandb: False # will be overriden if running on cluster
  run_name: 'heightscan-pretrain'

model:
  model_type: 'vae'
  latent_dim: 64
  pose_dim: 16
